package view;

import controller.controller;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JToggleButton;

/**
 * @author Tyler
 **/
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
        this.setVisible(true);
        controller control = new controller(this);
    }

    public void addMyListener(ActionListener listen){
        btnBrowse.addActionListener(listen);
        btnPlay.addActionListener(listen);
        btnStop.addActionListener(listen);
        btnPause.addActionListener(listen);
    }
    
    public JButton getBtnBrowse(){
        return btnBrowse;
    }
    
    public JButton getBtnPlay(){
        return btnPlay;
    }
    
    public JButton getBtnStop(){
        return btnStop;
    }
    
    public JButton getBtnPause(){
        return btnPause;
    }
    
    public String getTxtSong(){
        return this.txtSong.getText();
    }
    
    public String getTxtDirectory(){
        return this.txtDirectory.getText();
    }
    
    public void setTxtDirectory(String path){
        this.txtDirectory.setText(path);
    }
    
    public void setTxtSong(String name){
        this.txtSong.setText(name);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDirectory = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        btnPause = new javax.swing.JButton();
        txtSong = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Refactored Music Player");

        txtDirectory.setText("C:\\");
            txtDirectory.setToolTipText("");

            btnBrowse.setText("Browse");

            btnPlay.setText("Play");

            btnStop.setText("Stop");
            btnStop.setMaximumSize(new java.awt.Dimension(64, 25));
            btnStop.setMinimumSize(new java.awt.Dimension(64, 25));
            btnStop.setPreferredSize(new java.awt.Dimension(64, 25));

            btnPause.setText("Pause");

            txtSong.setEditable(false);
            txtSong.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
            txtSong.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            txtSong.setToolTipText("");
            txtSong.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtSongActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnPause)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtSong)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDirectory))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                    .addComponent(txtSong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPlay)
                        .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPause))
                    .addGap(19, 19, 19))
            );

            btnBrowse.getAccessibleContext().setAccessibleName("");

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void txtSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnStop;
    private javax.swing.JTextField txtDirectory;
    private javax.swing.JTextField txtSong;
    // End of variables declaration//GEN-END:variables
}
